# Generated by Django 4.1 on 2022-08-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('release_year', models.IntegerField()),
                ('poster', models.ImageField(upload_to='movies')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('actors', models.TextField()),
                ('genre', models.TextField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Crime and mystery', 'Crime and mystery'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Romance', 'Romance'), ('Satire', 'Satire'), ('Science fiction', 'Science fiction'), ('Thriller', 'Thriller'), ('Western', 'Western'), ('Other', 'Other')])),
            ],
        ),
    ]
